FROM taccwma/core-cms:fix-core-cms-template-gh-18
# Had once used taccwma/core-cms:448b6b30 (TACC/Core-CMS#885 v4.26.1+)

WORKDIR /code

COPY /src/apps /code/apps
COPY /src/taccsite_cms /code/taccsite_cms
